#!/bin/bash
#docker-compose build

ROOT=$(dirname $(dirname $(dirname $(pwd))))
APP=${PWD##*/}
docker run -ti --rm -v $ROOT:/tmp/hx -w /tmp/hx/AvrLibDemo/apps/${APP} -v /etc/group:/etc/group:ro -v /etc/passwd:/etc/passwd:ro --user=$UID jypma/avr-gcc make "$@"
