#!/bin/bash
#docker-compose build
docker run -ti --rm -v ~/Documents/workspace-arduino:/tmp/hx -w /tmp/hx/AvrLibDemo/apps/roomsensor -v /etc/group:/etc/group:ro -v /etc/passwd:/etc/passwd:ro --user=$UID jypma/avr-gcc make "$@"
